### ISSUE TITLE
Mostrar estudiantes activos en la vista de asigments

### ISSUE THREAD

**Issue by pbullor** [breatheco-de/apiv2#821]
La idea es que solo muestre los usuarios que están activos en su educational status.
![image](https://user-images.githubusercontent.com/70356168/226663132-c4989d15-5dca-4251-9344-b59c09c8ed0d.png)
![image](https://user-images.githubusercontent.com/70356168/226663312-96149504-9bcb-4c6d-acbc-784200c1f67a.png)

https://github.com/breatheco-de/apiv2/blob/04f110ae12ebccf9d285f546b92f035efe0f3c72/breathecode/assignments/views.py#L304

**Comment by tommygonzaleza** [comment]
Se cerrara el issue ya que se movio para [otro](https://github.com/4GeeksAcademy/About-4Geeks-Academy/issues/4694)
